# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dental Record
tagline:          'Administrative system for "The Californias Health System - Dental".'
description:      'Documentation for Dental Record. All you need to know to get up and running. Made by <a href="https://twitter.com/andiosuna" target="_blank">@andiosuna</a>.'
url:              http://andyosuna.github.io/dental-record

author:
  name:           'Andy Osuna'
  url:            https://twitter.com/andiosuna

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/andyosuna/dental-record
  download:       /archive/master.zip

bitbucket:
  repo:           https://bitbucket.org/mediexcel-dev/dental-record
  download:       /get/master.zip
