# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dental Record
tagline:          'Administrative system for "The Californias Health System - Dental".'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://andyosuna.github.io/dental-record

author:
  name:           'Andy Osuna'
  url:            https://twitter.com/andiosuna

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/andyosuna/dental-record
  download:       /archive/master.zip

bitbucket:
  repo:           https://bitbucket.org/mediexcel-dev/dentaldev
  download:       /get/master.zip
